name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup beam
      uses: erlef/setup-beam@v1.14
      with:
        elixir-version: 1.14
        otp-version: 25
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
